services:
  yq-runner:
    build: ./lang-runner
    security_opt:
      - seccomp:unconfined
    ports:
      - "3000:3000"
    volumes:
      - ./target/debug:/debug
    entrypoint: ['/debug/lang-runner']